texto = input("Digite nome, idade e email: ")
partes = texto.split(',')
tamanho1 = len(partes[0].strip()+ "nome: ")
tamanho2 = len(partes[1].strip()+ "idade: ")
tamanho3 = len(partes[2].strip()+ "Email: ")
maior = max(tamanho1, tamanho2, tamanho3)
print("-" * maior)
print(f'Nome: {partes[0].strip()}')
print(f'Idade: {partes[1].strip()}')
print(f'Email: {partes[2].strip()}')
print("-" * maior)